### ISSUE TITLE
Can't resolve 'react-native-web/dist/exports/AppRegistry'

### ISSUE THREAD

**Issue by mvillafuertem** [shadaj/expo-template-scala#2] opened 2019-12-23 20:43 UTC
```
Module not found: Can't resolve 'react-native-web/dist/exports/AppRegistry' 
in '/tmp/expo-template-scala/node_modules/expo/build/environment'
```

I get this error, when I try run the app.

` expo start --web`

`yarn add react-native-web react-dom expo`

```
 web  Failed to compile.
/tmp/expo-template-scala/node_modules/expo/build/Notifications/Notifications.js
Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage' in '/tmp/expo-template-scala/node_modules/expo/build/Notifications'
```

**Comment by msenkiv** [comment] 2020-01-08 16:47
same error

**Comment by msenkiv** [comment] 2020-01-08 16:54
if you need to use the AsyncStorage you can use the version: "react-native-web": "0.11.7",

**Comment by shadaj** [comment] 2020-03-16 22:11
Looks like this was fixed in a newer version of `react-native-web`, so closing for now! Please ping if this is still showing up.

**Comment by mvillafuertem** [comment] 2020-04-03 16:42
@shadaj Now I get this error. Any suggestion is welcome. Thanks

```
×
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
Module.<anonymous>
/expo-template-scala/App.js:5
  2 | import {Text, View} from 'react-native';
  3 | 
  4 | if (__DEV__) {
> 5 |   module.exports = require("./target/scala-2.13/scalajs-bundler/main/app-fastopt.js").app;
  6 | } else {
  7 |   module.exports = () => {
  8 |     return <View style={{flex: 1, justifyContent: "center", alignItems: "center"}}>
```

```
  "dependencies": {
    "expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native-web": "0.11.7",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-proxy": "1.1.8"
  }
```

**Comment by diegoboston** [comment] 2020-05-31 09:55
This happens to me too, out of the box for an empty app, following the basic setup instructions.

> expo init --template expo-template-scala
>  cd myapp
>  sbt fastOptJS
> npm start

I also run "npm install"

**Comment by diegoboston** [comment] 2020-05-31 10:09
@mvillafuertem @shadaj  I have the same issue if I follow the setup instructions. If you look at the terminal, you can see more details on the error - not sure how to fix it. It looks like the default template is not exporting "App" correctly, even if I see the export in hello/world/Main.scala.

-----

 web  Compiled with warnings.
..../node_modules/expo/AppEntry.js
Attempted import error: '../../App' does not contain a default export (imported as 'App').

-----

To reproduce:



  expo init --template expo-template-scala
   cd myapp/
  npm install
  yarn add react-native-web react-dom expo
   sbt fastOptJS
  npm start

**Comment by diegoboston** [comment] 2020-05-31 11:37
Ok, I have a fix @mvillafuertem. In the root dir of your project, change App.js as follows. This should get you going.

let app = require("./target/scala-2.12/app-fastopt.js").app;
export default app;

**Comment by mvillafuertem** [comment] 2020-05-31 18:06
> Ok, I have a fix @mvillafuertem. In the root dir of your project, change App.js as follows. This should get you going.
> 
> let app = require("./target/scala-2.12/app-fastopt.js").app;
> export default app;

This works for me. Thanks!!

**Comment by shadaj** [comment] 2020-05-31 18:12
What is your `scalaVersion` set to? The template now uses Scala 2.13 which is why the `App.js` loads from the `scala-2.13` folder.

**Comment by diegoboston** [comment] 2020-06-01 13:53
Beyond the scala version (I'm using 2.12), I believe the issue is that App.js is exporting incorrectly, at least in my compiled files.

It was using "old school" exports.
>   module.exports = require("./target/scala-XXX/scalajs-bundler/main/app-fastopt.js").app;

My fix is using more modern export syntax.
> let app = require("./target/scala-XXX/app-fastopt.js").app;
> export default app;

**Comment by thesamet** [comment] 2020-08-05 16:42
Have just experienced the same issue when trying out this template. I believe this issue should be re-opened as the template/getting-started instructions are not working. The steps I took to move forward was to install `react-native-web`:

```
yarn install react-native-web
```

Change App.js in its entirety to:
```
let app = require("./target/scala-2.13/app-fastopt.js").app;
export default app;
```

**Comment by shadaj** [comment] 2020-08-07 18:35
Hmm, looks like this is some issue with the way the app is bundled for the web. @thesamet would you be interested in creating a PR to change `App.js` as you described? Will probably need a bit more code so that `fullOpt` mode is supported as well.

**Comment by thesamet** [comment] 2020-08-07 18:48
Hey, thanks for re-opening. I was mostly passing by and checking out Slinky (which is awesome) and brushing up on what's available for Scala.js and Mobile. It's unlikely that I'll be able to put the time to get this PR right for production users (not working on a specific project right now)

**Closed as completed** 2020-10-04 23:57 UTC
